config/routes.rb
TopicTracker::Application.routes.draw do
  root 'topics#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get "/signout" => "sessions#destroy", as: :signout

  resources :topics do
    resources :votes
  end

  namespace :api do
    namespace :v1 do
      resources :topics, only: [:index, :create]
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :description

    def vote_from(user)
    votes.find_by(user_id: user.id)
  end

  def has_vote_from?(user)
    votes.find_by(user_id: user.id).present?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :uid, :name, :provider
  validates_uniqueness_of :uid
  has_many :topics
  has_many :votes

  def self.find_or_create_from_auth_hash(auth_hash)
    where(auth_hash.slice("provider", "uid")).first || create_from_omniauth(auth_hash)
  end

  def self.create_from_omniauth(auth_hash)
    create! do |user|
      user.provider = auth_hash["provider"]
      user.uid = auth_hash["uid"]
      user.name = auth_hash["info"]["nickname"]
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :topic
  belongs_to :user

  validates_presence_of :topic_id
  validates_presence_of :user_id
  validates_uniqueness_of :user_id, scope: [:topic_id]
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < ApplicationController
  before_filter :user_signed_in
  before_filter :user_made_post, only: [:edit, :update, :destroy]
  respond_to :json

  def index
    respond_with Topic.all
  end

  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      render json: @topic
    else
      render json: @topic.errors, status: :unprocessable_entity
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in
    render status: :forbidden if current_user.nil?
  end

  def user_made_post
    set_topic
    redirect_to root_path, notice: 'Not your post!' if @topic.user != current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_from_auth_hash(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :user_signed_in, except: :index
  before_filter :user_made_post, only: [:edit, :update, :destroy]
  def index
    @topics = Topic.all
  end

  def show
    set_topic
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      redirect_to topics_path, notice: 'Your topic was successfully created!'
    else
      render :new
    end
  end

  def edit
    set_topic
  end

  def update
    set_topic
    if @topic.update(topic_params)
      redirect_to topics_path, notice: 'Your topic was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    set_topic
    if @topic.destroy
      redirect_to root_path, notice: 'Topic successfully destroyed'
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description, :category)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :user_signed_in

  def create
    topic = Topic.find(params[:topic_id])
    vote = current_user.votes.build
    vote.topic = topic

    respond_to do |format|
      if vote.save
        format.html { redirect_to :back, notice: "Upvoted successfully!" }
        format.json { render json: vote }
      else
        format.html { redirect_to :back }
        format.json { render json: vote.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.votes.destroy(params[:id])

    respond_to do |format|
      # Respond the same way we were before if the request format is html
      format.html do
        flash[:notice] = "Vote removed."
        redirect_to :back
      end

      # Respond with a "204 No Content" to signify that the request has been
      # fulfilled
      format.json { head :no_content }
    end
  end

  private


  def user_signed_in
    redirect_to root_path, notice: 'Must sign in!' if current_user == nil
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TopicTracker</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" if current_user %>

  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  Signed in as <%= current_user.name %>!
  <%= link_to 'Sign Out', signout_path %>
<% else %>
  <%= link_to 'Sign In With GitHub', '/auth/github' %>
<% end %>

<p class='notice'><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |f| %>
  <%= f.input :title %><br>
  What would you like discussed?<br>
  The more information, the better we can help you.
  <%= f.input :description %><br>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<%= render "topics/form", topic: @topic %>

app/views/topics/index.html.erb
<% if false %>
<h1>Current Topics</h1>
<hr>
<% @topics.each do |topic| %>
  <h2><%= topic.category %> : <%= link_to topic.title, topic_path(topic) %></h2>
  <%= topic.description %><br><br>
  <%= link_to "Edit", edit_topic_path(topic) %>
  <%= link_to "Delete", topic, method: :delete %>
  <br><br><hr>

 <% if current_user != nil %>
      <% if topic.has_vote_from?(current_user) %>
        <%= button_to "Remove Vote", topic_vote_path(topic, topic.vote_from(current_user)),
          method: :delete,
          form: { data: { 'vote-button' => 'delete' } } %>
      <% else %>
        <%= button_to "Vote Up", topic_votes_path(topic),
          method: :post,
          form: { data: { 'vote-button' => 'create' } } %>
      <% end %>
    <% end %>

  <% end %>
<br><br>
<%= button_to 'Create a Topic', new_topic_path, method: :get %>
<% end %>

app/views/topics/new.html.erb
<h1>Have something you want discussed? Fill out the form below to add a topic!</h1>

<%= render "topics/form", topic: @topic %>

app/views/topics/show.html.erb
<h2><em>Topic created on: </em> <%= @topic.created_at.to_formatted_s(:long) %></h2>
<strong>The Issue: </strong><br>
<%= @topic.title %><br>
<strong>Description:</strong><br>
<%= @topic.description %>
<br><br><hr>
<%= link_to 'Edit', edit_topic_path(@topic) %> <%= link_to 'Back', topics_path %>

app/views/welcome/index.html.erb
<h1> Welcome Page </h1>

<% if current_user %>
  Signed in as <%= current_user.name %>!
  <%= link_to 'Sign Out', signout_path %>
<% else %>
  <%= link_to 'Sign In With GitHub', '/auth/github' %>
<% end %>

<%= link_to 'Topics', topics_path %>